<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	<UseBlazorWebAssembly>true</UseBlazorWebAssembly>
	<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	<PublishTrimmed>true</PublishTrimmed>
	<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	<RunAOTCompilation>false</RunAOTCompilation>
	<WasmStripILAfterAOT>true</WasmStripILAfterAOT>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gizmo.Go.UI\Gizmo.Go.UI.csproj" />
    <ProjectReference Include="..\Gizmo.Go.Core\Gizmo.Go.Core.csproj" />
    <ProjectReference Include="..\Gizmo.Go.Provider.Direct\Gizmo.Go.Provider.Direct.csproj" />
    <ProjectReference Include="..\Gizmo.Go.Provider.Platform\Gizmo.Go.Provider.Platform.csproj" />
  </ItemGroup>

</Project>
