using Gizmo.Go.Core.Models.Confirmation;

namespace Gizmo.Go.UI.Helpers;

public static class ConfirmationErrorHelper
{
    public static string GetLocalizationKey(TokenConfirmationResultCode code) => code switch
    {
        TokenConfirmationResultCode.InvalidConfirmationCode => nameof(Autogenerated.Resources.GO_CONFIRMATION_ERROR_INVALID_CODE),
        TokenConfirmationResultCode.ExpiredToken            => nameof(Autogenerated.Resources.GO_CONFIRMATION_ERROR_EXPIRED),
        TokenConfirmationResultCode.UsedToken               => nameof(Autogenerated.Resources.GO_CONFIRMATION_ERROR_USED),
        TokenConfirmationResultCode.RevokedToken            => nameof(Autogenerated.Resources.GO_CONFIRMATION_ERROR_REVOKED),
        _                                                   => nameof(Autogenerated.Resources.GO_CONFIRMATION_ERROR_GENERAL),
    };
}
