using Gizmo.Go.Core.Models.Registration;

namespace Gizmo.Go.UI.Helpers;

public static class RegistrationCompleteErrorHelper
{
    public static string GetLocalizationKey(RegistrationCompleteResultCode code) => code switch
    {
        RegistrationCompleteResultCode.InvalidToken      => nameof(Autogenerated.Resources.GO_REGISTRATION_COMPLETE_ERROR_INVALID_TOKEN),
        RegistrationCompleteResultCode.InvalidTokenInput => nameof(Autogenerated.Resources.GO_REGISTRATION_COMPLETE_ERROR_INVALID_TOKEN),
        RegistrationCompleteResultCode.ExpiredToken      => nameof(Autogenerated.Resources.GO_REGISTRATION_COMPLETE_ERROR_EXPIRED_TOKEN),
        RegistrationCompleteResultCode.UsedToken         => nameof(Autogenerated.Resources.GO_REGISTRATION_COMPLETE_ERROR_USED_TOKEN),
        RegistrationCompleteResultCode.RevokedToken      => nameof(Autogenerated.Resources.GO_REGISTRATION_COMPLETE_ERROR_REVOKED_TOKEN),
        _                                                => nameof(Autogenerated.Resources.GO_REGISTRATION_COMPLETE_ERROR_GENERAL),
    };
}
