//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Go.Web.Autogenerated {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Go.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gizmo Go.
        /// </summary>
        public static string GO_APP_TITLE {
            get {
                return ResourceManager.GetString("GO_APP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string GO_LOGIN_ERROR_UNEXPECTED {
            get {
                return ResourceManager.GetString("GO_LOGIN_ERROR_UNEXPECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login - Gizmo Go.
        /// </summary>
        public static string GO_LOGIN_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string GO_LOGIN_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string GO_LOGIN_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string GO_LOGIN_SUBMIT {
            get {
                return ResourceManager.GetString("GO_LOGIN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string GO_LOGIN_SUBMIT_LOADING {
            get {
                return ResourceManager.GetString("GO_LOGIN_SUBMIT_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string GO_LOGIN_USERNAME_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_USERNAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        public static string GO_LOGIN_USERNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_USERNAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string GO_VE_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_REQUIRED", resourceCulture);
            }
        }
    }
}
