using System.ComponentModel.DataAnnotations;
using Gizmo.Go.Core.Autogenerated;

namespace Gizmo.Go.Core.Services
{
    /// <summary>
    /// Authentication error code.
    /// </summary>
    public enum AuthErrorCode
    {
        /// <summary>
        /// Invalid credentials (wrong username or password).
        /// </summary>
        [Name("Invalid username or password.", nameof(Resources.GO_AUTH_ERROR_INVALID_CREDENTIALS))]
        InvalidCredentials,

        /// <summary>
        /// Connection to the server failed.
        /// </summary>
        [Name("Unable to connect to the server.", nameof(Resources.GO_AUTH_ERROR_CONNECTION_FAILED))]
        ConnectionFailed,

        /// <summary>
        /// An unexpected error occurred.
        /// </summary>
        [Name("An unexpected error occurred.", nameof(Resources.GO_AUTH_ERROR_UNEXPECTED))]
        Unexpected,
    }
}
