//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Go.UI.Autogenerated {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Gizmo.Go.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GO_APP_TITLE {
            get {
                return ResourceManager.GetString("GO_APP_TITLE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_USERNAME_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_USERNAME_LABEL", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_USERNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_USERNAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_SUBMIT {
            get {
                return ResourceManager.GetString("GO_LOGIN_SUBMIT", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_SUBMIT_LOADING {
            get {
                return ResourceManager.GetString("GO_LOGIN_SUBMIT_LOADING", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PAGE_HEADING {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_HEADING", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PAGE_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_SUBTITLE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_TAB_PHONE {
            get {
                return ResourceManager.GetString("GO_LOGIN_TAB_PHONE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_TAB_NICKNAME {
            get {
                return ResourceManager.GetString("GO_LOGIN_TAB_NICKNAME", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_PHONE_LABEL", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PHONE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_PHONE_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("GO_LOGIN_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_NO_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_LOGIN_NO_ACCOUNT", resourceCulture);
            }
        }
        
        public static string GO_VE_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_VE_PHONE_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_PHONE_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_VE_PHONE_INVALID {
            get {
                return ResourceManager.GetString("GO_VE_PHONE_INVALID", resourceCulture);
            }
        }
        
        public static string GO_VE_PHONE_COUNTRY_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_PHONE_COUNTRY_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_VE_TERMS_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_TERMS_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_WELCOME_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_SECTION_LABEL {
            get {
                return ResourceManager.GetString("GO_WELCOME_SECTION_LABEL", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_TITLE_LINE1 {
            get {
                return ResourceManager.GetString("GO_WELCOME_TITLE_LINE1", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_TITLE_LINE2 {
            get {
                return ResourceManager.GetString("GO_WELCOME_TITLE_LINE2", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_DESCRIPTION {
            get {
                return ResourceManager.GetString("GO_WELCOME_DESCRIPTION", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_SIGN_IN {
            get {
                return ResourceManager.GetString("GO_WELCOME_SIGN_IN", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CREATE_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_WELCOME_CREATE_ACCOUNT", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CONTINUE_AS_GUEST {
            get {
                return ResourceManager.GetString("GO_WELCOME_CONTINUE_AS_GUEST", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_FIND_CLUB {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_FIND_CLUB", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_BOOK_PC {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_BOOK_PC", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_QR_LOGIN {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_QR_LOGIN", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_TOP_UP {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_TOP_UP", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_NEWS {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_NEWS", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_HEADING {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_HEADING", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_SUBTITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_COUNTRY_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_COUNTRY_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_COUNTRY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_COUNTRY_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_PHONE_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_PHONE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_PHONE_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_PREFIX {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_PREFIX", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_LINK1 {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_LINK1", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_AND {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_AND", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_LINK2 {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_LINK2", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_SUFFIX {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_SUFFIX", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_SUBMIT {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_SUBMIT", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_HAS_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_HAS_ACCOUNT", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_SIGN_IN {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_SIGN_IN", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_HEADING {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_HEADING", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_SUBTITLE_PREFIX {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_SUBTITLE_PREFIX", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_SUBTITLE_SUFFIX {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_SUBTITLE_SUFFIX", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_TIMER_PREFIX {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_TIMER_PREFIX", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_RESEND {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_RESEND", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_CHANGE_NUMBER {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_CHANGE_NUMBER", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_SUBMIT {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_SUBMIT", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_HINT {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_HINT", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_BACK {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_BACK", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_HEADING {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_HEADING", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_SUBTITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_BACK {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_BACK", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_CONFIRM_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_CONFIRM_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQUIREMENTS_TITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQUIREMENTS_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_LENGTH {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_LENGTH", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_UPPERCASE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_UPPERCASE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_DIGIT {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_DIGIT", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_SPECIAL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_SPECIAL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_SUBMIT {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_SUBMIT", resourceCulture);
            }
        }
    }
}
