//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Go.UI.Autogenerated {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Gizmo.Go.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GO_APP_TITLE {
            get {
                return ResourceManager.GetString("GO_APP_TITLE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_USERNAME_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_USERNAME_LABEL", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_USERNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_USERNAME_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_SUBMIT {
            get {
                return ResourceManager.GetString("GO_LOGIN_SUBMIT", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_SUBMIT_LOADING {
            get {
                return ResourceManager.GetString("GO_LOGIN_SUBMIT_LOADING", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PAGE_HEADING {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_HEADING", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PAGE_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_LOGIN_PAGE_SUBTITLE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_TAB_PHONE {
            get {
                return ResourceManager.GetString("GO_LOGIN_TAB_PHONE", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_TAB_NICKNAME {
            get {
                return ResourceManager.GetString("GO_LOGIN_TAB_NICKNAME", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_LOGIN_PHONE_LABEL", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_PHONE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_LOGIN_PHONE_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("GO_LOGIN_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        public static string GO_LOGIN_NO_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_LOGIN_NO_ACCOUNT", resourceCulture);
            }
        }
        
        public static string GO_VE_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_VE_PHONE_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_PHONE_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_VE_PHONE_INVALID {
            get {
                return ResourceManager.GetString("GO_VE_PHONE_INVALID", resourceCulture);
            }
        }
        
        public static string GO_VE_PHONE_COUNTRY_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_PHONE_COUNTRY_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_VE_TERMS_REQUIRED {
            get {
                return ResourceManager.GetString("GO_VE_TERMS_REQUIRED", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_WELCOME_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_SECTION_LABEL {
            get {
                return ResourceManager.GetString("GO_WELCOME_SECTION_LABEL", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_TITLE_LINE1 {
            get {
                return ResourceManager.GetString("GO_WELCOME_TITLE_LINE1", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_TITLE_LINE2 {
            get {
                return ResourceManager.GetString("GO_WELCOME_TITLE_LINE2", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_DESCRIPTION {
            get {
                return ResourceManager.GetString("GO_WELCOME_DESCRIPTION", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_SIGN_IN {
            get {
                return ResourceManager.GetString("GO_WELCOME_SIGN_IN", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CREATE_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_WELCOME_CREATE_ACCOUNT", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CONTINUE_AS_GUEST {
            get {
                return ResourceManager.GetString("GO_WELCOME_CONTINUE_AS_GUEST", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_FIND_CLUB {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_FIND_CLUB", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_BOOK_PC {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_BOOK_PC", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_QR_LOGIN {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_QR_LOGIN", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_TOP_UP {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_TOP_UP", resourceCulture);
            }
        }
        
        public static string GO_WELCOME_CHIP_NEWS {
            get {
                return ResourceManager.GetString("GO_WELCOME_CHIP_NEWS", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_HEADING {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_HEADING", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_SUBTITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_COUNTRY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_COUNTRY_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_PHONE_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_PHONE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_PHONE_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_PREFIX {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_PREFIX", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_LINK1 {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_LINK1", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_AND {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_AND", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_LINK2 {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_LINK2", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_TERMS_SUFFIX {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_TERMS_SUFFIX", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_SUBMIT {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_SUBMIT", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_HAS_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_HAS_ACCOUNT", resourceCulture);
            }
        }
        
        public static string GO_CREATE_ACCOUNT_SIGN_IN {
            get {
                return ResourceManager.GetString("GO_CREATE_ACCOUNT_SIGN_IN", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_HEADING {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_HEADING", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_SUBTITLE_PREFIX {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_SUBTITLE_PREFIX", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_SUBTITLE_SUFFIX {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_SUBTITLE_SUFFIX", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_TIMER_PREFIX {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_TIMER_PREFIX", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_RESEND {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_RESEND", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_CHANGE_NUMBER {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_CHANGE_NUMBER", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_SUBMIT {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_SUBMIT", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_HINT {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_HINT", resourceCulture);
            }
        }
        
        public static string GO_CONFIRMATION_BACK {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_BACK", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_ERROR_INVALID_CODE {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_ERROR_INVALID_CODE", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_ERROR_EXPIRED {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_ERROR_EXPIRED", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_ERROR_USED {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_ERROR_USED", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_ERROR_REVOKED {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_ERROR_REVOKED", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_ERROR_GENERAL {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_ERROR_GENERAL", resourceCulture);
            }
        }

        public static string GO_CREATE_PASSWORD_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PAGE_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_HEADING {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_HEADING", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_SUBTITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_BACK {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_BACK", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_PASSWORD_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PASSWORD_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_PASSWORD_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PASSWORD_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_CONFIRM_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_CONFIRM_PLACEHOLDER", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQUIREMENTS_TITLE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQUIREMENTS_TITLE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_LENGTH {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_LENGTH", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_UPPERCASE {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_UPPERCASE", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_DIGIT {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_DIGIT", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_REQ_SPECIAL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQ_SPECIAL", resourceCulture);
            }
        }
        
        public static string GO_CREATE_PASSWORD_SUBMIT {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_SUBMIT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_COMPLETE_ERROR_INVALID_TOKEN {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_COMPLETE_ERROR_INVALID_TOKEN", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_COMPLETE_ERROR_EXPIRED_TOKEN {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_COMPLETE_ERROR_EXPIRED_TOKEN", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_COMPLETE_ERROR_USED_TOKEN {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_COMPLETE_ERROR_USED_TOKEN", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_COMPLETE_ERROR_REVOKED_TOKEN {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_COMPLETE_ERROR_REVOKED_TOKEN", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_COMPLETE_ERROR_GENERAL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_COMPLETE_ERROR_GENERAL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_USERNAME_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_USERNAME_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_USERNAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_USERNAME_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_EMAIL_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_EMAIL_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_EMAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_EMAIL_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_FIRST_NAME_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_FIRST_NAME_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_FIRST_NAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_FIRST_NAME_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_LAST_NAME_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_LAST_NAME_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_LAST_NAME_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_LAST_NAME_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_BIRTH_DATE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_BIRTH_DATE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_ADDRESS_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_ADDRESS_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_ADDRESS_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_ADDRESS_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_CITY_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_CITY_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_CITY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_CITY_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_COUNTRY_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_COUNTRY_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_COUNTRY_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_COUNTRY_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_POST_CODE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_POST_CODE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_POST_CODE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_POST_CODE_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_PHONE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_MOBILE_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_MOBILE_PHONE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SEX_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SEX_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SEX_UNSPECIFIED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SEX_UNSPECIFIED", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SEX_MALE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SEX_MALE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SEX_FEMALE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SEX_FEMALE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SUBMIT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SUBMIT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_BACK {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_BACK", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_STEPPER_ACCOUNT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_STEPPER_ACCOUNT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_STEPPER_PROFILE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_STEPPER_PROFILE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_BIRTH_DATE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_BIRTH_DATE_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_NOTIFICATIONS_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_NOTIFICATIONS_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_NOTIFICATIONS_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_NOTIFICATIONS_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_NOTIFICATIONS_HINT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_NOTIFICATIONS_HINT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_SKIP {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_SKIP", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_NOTE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_NOTE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_BACK {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_BACK", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_LOADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_LOADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_EMPTY {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_EMPTY", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_ALT_DIVIDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_ALT_DIVIDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_ALT_DESCRIPTION {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_ALT_DESCRIPTION", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_ERROR_START {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_ERROR_START", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_CONTINUE_WITH {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_CONTINUE_WITH", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_TERMS_PREFIX {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_TERMS_PREFIX", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_TERMS_LINK1 {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_TERMS_LINK1", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_TERMS_AND {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_TERMS_AND", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROVIDERS_TERMS_LINK2 {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROVIDERS_TERMS_LINK2", resourceCulture);
            }
        }

        public static string GO_EYE_TOGGLE_SHOW {
            get {
                return ResourceManager.GetString("GO_EYE_TOGGLE_SHOW", resourceCulture);
            }
        }

        public static string GO_EYE_TOGGLE_HIDE {
            get {
                return ResourceManager.GetString("GO_EYE_TOGGLE_HIDE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_WAITING_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_WAITING_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_WAITING_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_WAITING_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_WAITING_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_WAITING_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_TELEGRAM_CONFIRMED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_TELEGRAM_CONFIRMED", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_TELEGRAM_CONNECTED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_TELEGRAM_CONNECTED", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_PHONE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_PHONE_VERIFIED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_PHONE_VERIFIED", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_INFO_TEXT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_INFO_TEXT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_BOT_VERIFY_SUBMIT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_BOT_VERIFY_SUBMIT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_CHIP_PC {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_CHIP_PC", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_CHIP_BALANCE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_CHIP_BALANCE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_CHIP_QUICK_LOGIN {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_CHIP_QUICK_LOGIN", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_SUBMIT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_SUBMIT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_SUCCESS_NOTE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_SUCCESS_NOTE", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_OTP_GROUP_ARIA {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_OTP_GROUP_ARIA", resourceCulture);
            }
        }

        public static string GO_CONFIRMATION_OTP_DIGIT_ARIA {
            get {
                return ResourceManager.GetString("GO_CONFIRMATION_OTP_DIGIT_ARIA", resourceCulture);
            }
        }

        public static string GO_CREATE_PASSWORD_PHONE_VERIFIED_LABEL {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_PHONE_VERIFIED_LABEL", resourceCulture);
            }
        }

        public static string GO_CREATE_PASSWORD_REQUIREMENTS_ARIA {
            get {
                return ResourceManager.GetString("GO_CREATE_PASSWORD_REQUIREMENTS_ARIA", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_STEPPER_ARIA {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_STEPPER_ARIA", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_PROFILE_STEP_DONE_ARIA {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_PROFILE_STEP_DONE_ARIA", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_HINT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_HINT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_OR {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_OR", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ALT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ALT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_CONFIRMATION_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_CONFIRMATION_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_CONFIRMATION_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_CONFIRMATION_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_CONFIRMATION_SUBTITLE_PREFIX {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_CONFIRMATION_SUBTITLE_PREFIX", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_CONFIRMATION_SUBTITLE_SUFFIX {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_CONFIRMATION_SUBTITLE_SUFFIX", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_CONFIRMATION_CHANGE_EMAIL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_CONFIRMATION_CHANGE_EMAIL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_CONFIRMATION_HINT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_CONFIRMATION_HINT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_EMAIL_CONFIRMED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_EMAIL_CONFIRMED", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_PHONE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_PHONE_PLACEHOLDER {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_PHONE_PLACEHOLDER", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_INFO {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_INFO", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_EMAIL_ADD_PHONE_SUBMIT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_EMAIL_ADD_PHONE_SUBMIT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_SUBTITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_SUBTITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_STEP1 {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_STEP1", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_STEP2 {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_STEP2", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_STEP3 {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_STEP3", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_LABEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_LABEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_SUBMIT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_SUBMIT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_HINT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_HINT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_PHONE_BACK {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_PHONE_BACK", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_BACK {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_BACK", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_INSTRUCTION {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_INSTRUCTION", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_CHANGE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_CHANGE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_COPY_HINT {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_COPY_HINT", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_INFO {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_INFO", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_TIMER_PREFIX {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_TIMER_PREFIX", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_VERIFY_CANCEL {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_VERIFY_CANCEL", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_SUCCESS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_SUCCESS_PAGE_TITLE", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_SUCCESS_HEADING {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_SUCCESS_HEADING", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_SUCCESS_SUBTITLE_PREFIX {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_SUCCESS_SUBTITLE_PREFIX", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_SUCCESS_SUBTITLE_SUFFIX {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_SUCCESS_SUBTITLE_SUFFIX", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_SUCCESS_VERIFIED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_SUCCESS_VERIFIED", resourceCulture);
            }
        }

        public static string GO_REGISTRATION_CALL_SUCCESS_CALL_RECEIVED {
            get {
                return ResourceManager.GetString("GO_REGISTRATION_CALL_SUCCESS_CALL_RECEIVED", resourceCulture);
            }
        }
    }
}
