using System.ComponentModel.DataAnnotations;
using Gizmo.UI;
using Gizmo.UI.View.States;
using Microsoft.Extensions.DependencyInjection;

namespace Gizmo.Go.UI.View.States.Pages
{
    [Register()]
    public sealed class LoginViewState : ValidatingViewStateBase
    {
        [ValidatingProperty()]
        [Required(ErrorMessageResourceType = typeof(Autogenerated.Resources), ErrorMessageResourceName = nameof(Autogenerated.Resources.GO_VE_REQUIRED))]
        public string Username { get; internal set; } = string.Empty;

        [ValidatingProperty()]
        [Required(ErrorMessageResourceType = typeof(Autogenerated.Resources), ErrorMessageResourceName = nameof(Autogenerated.Resources.GO_VE_REQUIRED))]
        public string Password { get; internal set; } = string.Empty;

        public bool IsLoading { get; internal set; }

        public string? ErrorMessage { get; internal set; }
    }
}
