using System.Web;
using Gizmo.Go.Core.Models.Registration;
using Gizmo.Go.Core.Services;
using Gizmo.Go.UI.Helpers;
using Gizmo.Go.UI.View.States.Pages.Registration;
using Gizmo.UI.Services;
using Gizmo.UI.View.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Gizmo.Go.UI.View.Services.Pages.Registration;

[Register()]
[Route(NavigationHelper.RegistrationProviders)]
public class RegistrationProvidersViewService : ViewStateServiceBase<RegistrationProvidersViewState>
{
    #region CONSTRUCTOR

    private readonly IRegistrationService _registrationService;
    private readonly NavigationService _navigationService;
    private readonly IExternalLauncher _externalLauncher;
    private readonly ILocalizationService _localizationService;

    public RegistrationProvidersViewService(
        RegistrationProvidersViewState viewState,
        ILogger<RegistrationProvidersViewService> logger,
        IServiceProvider serviceProvider,
        IRegistrationService registrationService,
        NavigationService navigationService,
        IExternalLauncher externalLauncher,
        ILocalizationService localizationService)
        : base(viewState, logger, serviceProvider)
    {
        _registrationService = registrationService;
        _navigationService = navigationService;
        _externalLauncher = externalLauncher;
        _localizationService = localizationService;
    }

    #endregion

    #region METHODS

    public async Task SelectProviderAsync(Guid channelGuid, CancellationToken cancellationToken = default)
    {
        var provider = ViewState.Providers.FirstOrDefault(p => p.ChannelGuid == channelGuid);
        if (provider is null)
            return;

        ViewState.HasError = false;
        ViewState.ErrorMessage = string.Empty;
        ViewState.FailedChannelGuid = null;
        ViewState.RaiseChanged();

        if (provider is { CanDispatchCode: true, CanRedirect: false })
        {
            _navigationService.NavigateTo($"{NavigationHelper.RegistrationPhone}?provider={provider.PublicId}");
            return;
        }

        if (provider.CanRedirect)
        {
            try
            {
                var request = new RegistrationStartRequest
                {
                    IntegrationPublicId = provider.PublicId,
                    DeliveryMethod = RegistrationDeliveryMethod.Redirect
                };
                var result = await _registrationService.StartAsync(request, cancellationToken);

                if (result.Result == RegistrationStartResultCode.Success
                    && !string.IsNullOrEmpty(result.RedirectUrl))
                {
                    await _externalLauncher.OpenAsync(result.RedirectUrl, cancellationToken);
                }
                else
                {
                    SetProviderError(channelGuid);
                }
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, "Failed to start redirect registration for provider {ChannelGuid}.", channelGuid);
                SetProviderError(channelGuid);
            }
        }
    }

    private void SetProviderError(Guid channelGuid)
    {
        ViewState.HasError = true;
        ViewState.ErrorMessage = _localizationService.GetString(nameof(Autogenerated.Resources.GO_REGISTRATION_PROVIDERS_ERROR_START));
        ViewState.FailedChannelGuid = channelGuid;
        ViewState.RaiseChanged();
    }

    #endregion

    #region OVERRIDES

    protected override async Task OnNavigatedIn(NavigationParameters navigationParameters,
        CancellationToken cancellationToken = default)
    {
        var uri = new Uri(_navigationService.GetUri());
        var errorParam = HttpUtility.ParseQueryString(uri.Query).Get("error");
        var hasError = errorParam == "1";

        ViewState.HasError = hasError;
        ViewState.ErrorMessage = hasError
            ? _localizationService.GetString(nameof(Autogenerated.Resources.GO_REGISTRATION_PROVIDERS_ERROR_START))
            : string.Empty;
        ViewState.IsLoading = true;
        ViewState.RaiseChanged();

        try
        {
            ViewState.Providers = await _registrationService.GetProvidersAsync(cancellationToken);
        }
        finally
        {
            ViewState.IsLoading = false;
            ViewState.RaiseChanged();
        }

        await base.OnNavigatedIn(navigationParameters, cancellationToken);
    }

    public ValueTask NavigateBackAsync()
    {
        _navigationService.NavigateTo(NavigationHelper.WelcomePage);
        return ValueTask.CompletedTask;
    }

    public ValueTask NavigateToLoginAsync()
    {
        _navigationService.NavigateTo(NavigationHelper.LoginPage);
        return ValueTask.CompletedTask;
    }

    #endregion
}
