using Gizmo.Go.UI.View.Models;
using Gizmo.Go.UI.View.States.Pages;
using UiResources = Gizmo.Go.UI.Autogenerated.Resources;
using Gizmo.UI.Services;
using Gizmo.UI.View.Services;
using Microsoft.AspNetCore.Components;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Gizmo.Go.UI.View.Services.Pages
{
    [Register()]
    [Route("/create-account")]
    public sealed class CreateAccountViewService : ValidatingViewStateServiceBase<CreateAccountViewState>
    {
        #region CONSTRUCTOR

        private readonly NavigationService _navigationService;

        public CreateAccountViewService(
            CreateAccountViewState viewState,
            ILogger<CreateAccountViewService> logger,
            IServiceProvider serviceProvider,
            NavigationService navigationService) : base(viewState, logger, serviceProvider)
        {
            _navigationService = navigationService;
        }

        #endregion

        #region METHODS

        public ValueTask UpdatePhoneAsync(PhoneInputChangedModel model)
        {
            ViewState.PhoneInput = model.Input;
            ViewState.SelectedCountryIso2 = model.CountryIso2;
            ViewState.SelectedCountryName = model.CountryName;
            ViewState.SelectedDialCode = model.DialCode;
            ViewState.PhoneE164 = model.IsValid ? model.E164 : string.Empty;
            ViewState.IsPhoneValid = model.IsValid;
            ViewState.PhoneValidationMessage = GetPhoneValidationMessage(model);
            ViewState.RaiseChanged();

            return ValueTask.CompletedTask;
        }

        public ValueTask ToggleTermsAsync()
        {
            ViewState.TermsAccepted = !ViewState.TermsAccepted;
            if (ViewState.TermsAccepted)
                ViewState.TermsValidationMessage = null;
            ViewState.RaiseChanged();
            return ValueTask.CompletedTask;
        }

        public ValueTask SubmitAsync()
        {
            RefreshValidationMessages();

            if (!ViewState.IsFormValid)
            {
                ViewState.RaiseChanged();
                return ValueTask.CompletedTask;
            }

            var encodedPhone = Uri.EscapeDataString(ViewState.PhoneE164);
            _navigationService.NavigateTo($"/confirmation?phone={encodedPhone}");
            return ValueTask.CompletedTask;
        }

        public ValueTask NavigateBackAsync()
        {
            _navigationService.NavigateTo("/login");
            return ValueTask.CompletedTask;
        }

        #endregion

        #region OVERRIDES

        protected override Task OnNavigatedIn(NavigationParameters navigationParameters, CancellationToken cancellationToken = default)
        {
            ViewState.PhoneInput = string.Empty;
            ViewState.SelectedCountryIso2 = string.Empty;
            ViewState.SelectedCountryName = string.Empty;
            ViewState.SelectedDialCode = string.Empty;
            ViewState.PhoneE164 = string.Empty;
            ViewState.IsPhoneValid = false;
            ViewState.PhoneValidationMessage = null;
            ViewState.TermsAccepted = false;
            ViewState.TermsValidationMessage = null;
            ViewState.RaiseChanged();
            return base.OnNavigatedIn(navigationParameters, cancellationToken);
        }

        #endregion

        #region HELPERS

        private void RefreshValidationMessages()
        {
            if (string.IsNullOrWhiteSpace(ViewState.SelectedCountryIso2))
            {
                ViewState.PhoneValidationMessage = UiResources.GO_VE_PHONE_COUNTRY_REQUIRED;
            }
            else if (string.IsNullOrWhiteSpace(ViewState.PhoneInput))
            {
                ViewState.PhoneValidationMessage = UiResources.GO_VE_PHONE_REQUIRED;
            }
            else if (!ViewState.IsPhoneValid)
            {
                ViewState.PhoneValidationMessage ??= UiResources.GO_VE_PHONE_INVALID;
            }
            else
            {
                ViewState.PhoneValidationMessage = null;
            }

            ViewState.TermsValidationMessage = ViewState.TermsAccepted
                ? null
                : UiResources.GO_VE_TERMS_REQUIRED;
        }

        private static string? GetPhoneValidationMessage(PhoneInputChangedModel model)
        {
            if (string.IsNullOrWhiteSpace(model.CountryIso2))
            {
                return UiResources.GO_VE_PHONE_COUNTRY_REQUIRED;
            }

            if (string.IsNullOrWhiteSpace(model.Input))
            {
                return null;
            }

            return model.ValidationError switch
            {
                nameof(UiResources.GO_VE_PHONE_INVALID) => UiResources.GO_VE_PHONE_INVALID,
                _ => model.IsValid ? null : UiResources.GO_VE_PHONE_INVALID
            };
        }

        #endregion
    }
}
