using System.ComponentModel.DataAnnotations;
using Gizmo.UI;
using Gizmo.UI.View.States;
using Microsoft.Extensions.DependencyInjection;

namespace Gizmo.Go.UI.View.States.Pages.Registration
{
    [Register()]
    public sealed class RegistrationProfileViewState : ValidatingViewStateBase
    {
        [ValidatingProperty(IsAsync = true)]
        [Required(ErrorMessageResourceType = typeof(Autogenerated.Resources), ErrorMessageResourceName = nameof(Autogenerated.Resources.GO_VE_REQUIRED))]
        public string Username { get; internal set; } = string.Empty;

        public string FirstName { get; internal set; } = string.Empty;
        public string LastName { get; internal set; } = string.Empty;
        public DateTime? BirthDate { get; internal set; }

        public bool IsSubmitting { get; internal set; }
        public string? ErrorMessage { get; internal set; }
    }
}
