using System.ComponentModel.DataAnnotations;
using Gizmo.UI;
using Gizmo.UI.View.States;
using Microsoft.Extensions.DependencyInjection;

namespace Gizmo.Go.UI.View.States.Pages.Registration
{
    [Register()]
    public sealed class RegistrationEmailViewState : ValidatingViewStateBase
    {
        [ValidatingProperty()]
        [Required(ErrorMessageResourceType = typeof(Autogenerated.Resources), ErrorMessageResourceName = nameof(Autogenerated.Resources.GO_VE_REQUIRED))]
        [EmailAddress(ErrorMessageResourceType = typeof(Autogenerated.Resources), ErrorMessageResourceName = nameof(Autogenerated.Resources.GO_VE_EMAIL_INVALID))]
        public string Email { get; internal set; } = string.Empty;

        public Guid IntegrationPublicId { get; internal set; }
        public bool IsSubmitting { get; internal set; }

        public bool CanSubmit => IsValid == true && !IsSubmitting;
    }
}
